version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tp3
      POSTGRES_USER: tp3_user
      POSTGRES_PASSWORD: tp3_pass
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./services/xml-service/app/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  xml-service:
    build: ./services/xml-service
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tp3
      DB_USER: tp3_user
      DB_PASSWORD: tp3_pass
    ports:
      - "8000:8000"
    depends_on:
      - db

  bi-service:
    build:
      context: .
      dockerfile: services/bi-service/Dockerfile
    environment:
      XML_SERVICE_BASE_URL: http://xml-service:8000
      BI_PORT: 3000
      DEMO_MODE: ${DEMO_MODE}
    ports:
      - "3000:3000"
    depends_on:
      - xml-service

  rpc-service:
    build: ./services/rpc-service
    environment:
      RPC_PORT: 7000
    ports:
      - "7000:7000"

  grpc-service:
    build: ./services/grpc-service
    environment:
      GRPC_PORT: 6000
    ports:
      - "6000:6000"

volumes:
  db_data:
